GARDEN_HOSTNAME=garden
GARDEN_USER=j

ILLUMINATOR_PORT=$ILLUMINATOR_PORT
SIMULATOR_PORT=$ILLUMINATOR_SIMULATOR_PORT

if [ ! "ILLUMINATOR_PORT" ]; then
  ILLUMINATOR_PORT="/dev/ttyUSB0"
fi
if [ ! "SIMULATOR_PORT" ]; then
  SIMULATOR_PORT="/dev/ttyUSB1"
fi

